/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DraftPanel.java
 *
 * Created on 21 Aug, 2011, 12:48:19 PM
 */
package emailplus;

import emailplus.operations.DBOperations;
import emailplus.operations.UserMailBean;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author deepika
 */
public class DraftPanel extends javax.swing.JPanel implements ListSelectionListener{

    /** Creates new form DraftPanel */
    DBOperations obj=null;
    ArrayList al=null;
    int configId;
    UserMailBean objBean=null;
    int currentSelected;
    public DraftPanel() {
        initComponents();
        txtContent.setEditable(false);
        btnCompose.setEnabled(false);
        btnDiscard.setEnabled(false);
        configId=MailAccountManager.configid;
        obj=new DBOperations();
        al=obj.getAllDrafts(configId);
            showDrafts();
            DraftTable.getSelectionModel().addListSelectionListener(this);
    }
    public void showDrafts()
    {
        if(al.isEmpty())
        {
            lblMessage.setText("There are no items to show in this folders");
            DraftTable.setEnabled(false);
            return;
            //JOptionPane.showMessageDialog(this, "no record", "Message", 1);
        }
        String header[]={"To","Subject","Sent Date"};
        Object data[][]=new Object[al.size()][3];
        for(int i=0;i<al.size();i++)
        {
            UserMailBean objBean=(UserMailBean)al.get(i);
            data[i][0]=objBean.getTo();
            data[i][1]=objBean.getSubject();
            data[i][2]=objBean.getDate();
        }
        DraftTable=new JTable(new DefaultTableStructure(data,header));
        jScrollPane.setViewportView(DraftTable);
        p.setVisible(false);
        p.setVisible(true);

    }

    public void valueChanged(ListSelectionEvent e) {
        currentSelected=DraftTable.getSelectedRow();
        objBean=(UserMailBean)al.get(currentSelected);
        txtContent.setText(objBean.getContent());
        lblTo.setText("To:   "+objBean.getTo());
        lblSubject.setText("Subject:   "+objBean.getSubject());
        btnCompose.setEnabled(true);
        btnDiscard.setEnabled(true);
        //System.out.println(i);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMessage = new javax.swing.JLabel();
        p = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        DraftTable = new javax.swing.JTable();
        lblSubject = new javax.swing.JLabel();
        lblTo = new javax.swing.JLabel();
        btnCompose = new javax.swing.JButton();
        btnDiscard = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtContent = new javax.swing.JTextArea();

        DraftTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "To", "Subject", "Saved Date"
            }
        ));
        jScrollPane.setViewportView(DraftTable);

        lblSubject.setText("Subject:");

        lblTo.setText("To:");

        btnCompose.setText("Compose");
        btnCompose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComposeActionPerformed(evt);
            }
        });

        btnDiscard.setText("Discard Draft");
        btnDiscard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiscardActionPerformed(evt);
            }
        });

        txtContent.setColumns(20);
        txtContent.setRows(5);
        jScrollPane1.setViewportView(txtContent);

        javax.swing.GroupLayout pLayout = new javax.swing.GroupLayout(p);
        p.setLayout(pLayout);
        pLayout.setHorizontalGroup(
            pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pLayout.createSequentialGroup()
                        .addComponent(btnCompose, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDiscard, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pLayout.createSequentialGroup()
                        .addComponent(lblSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTo, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(101, 101, 101))
            .addGroup(pLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
                .addContainerGap())
        );
        pLayout.setVerticalGroup(
            pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCompose)
                    .addComponent(btnDiscard))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(211, Short.MAX_VALUE))
            .addComponent(p, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnComposeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComposeActionPerformed
        // TODO add your handling code here:
        String subject=objBean.getSubject();
        String content=objBean.getContent();
        String to=objBean.getTo();
        MailAccountManager.p.removeAll();
        ComposePanel comobj=new ComposePanel();
        comobj.setBounds(0, 0, 1081, 563);
        comobj.setMessage(to, subject, content);
        MailAccountManager.p.add(comobj);
        MailAccountManager.p.setVisible(false);
        MailAccountManager.p.setVisible(true);
    }//GEN-LAST:event_btnComposeActionPerformed

    private void btnDiscardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiscardActionPerformed
        // TODO add your handling code here:
        if(obj.deleteDraftRecord(objBean).equals("deleted"))
        {
            MailAccountManager.p.removeAll();
            DraftPanel drobj=new DraftPanel();
            //System.out.println(objBean.getUsername());
            drobj.setBounds(0, 0, 1081,630 );
            MailAccountManager.p.add(drobj);
            MailAccountManager.p.setVisible(false);
            MailAccountManager.p.setVisible(true);
        }
    }//GEN-LAST:event_btnDiscardActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DraftTable;
    private javax.swing.JButton btnCompose;
    private javax.swing.JButton btnDiscard;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblSubject;
    private javax.swing.JLabel lblTo;
    private javax.swing.JPanel p;
    private javax.swing.JTextArea txtContent;
    // End of variables declaration//GEN-END:variables
}
