/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on Jun 30, 2011, 10:40:01 AM
 */

package emailplus;

import emailplus.operations.DBOperations;
import emailplus.operations.UsermasterBean;
import java.awt.Container;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;

/**
 *
 * @author Vishal
 */
public class MainFrame extends javax.swing.JFrame implements WindowListener{

    /** Creates new form MainFrame */
    public static Container c;
    public static int userid;
    public String username;
    public MainFrame(UsermasterBean objBean)
    {
        initComponents();
        c=this.getContentPane();
        userid=objBean.getUserId();
        username=objBean.getUsername();
        setResizable(false);
        setSize(Toolkit.getDefaultToolkit().getScreenSize());
        c.setLayout(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        if(!objBean.getUserType().equals("Administrator"))
        {
            //mnuUserMaintenance.setEnabled(false);
            //mnuReport.setEnabled(false);
            MenuBar.remove(mnuUserMaintenance);
            MenuBar.remove(mnuReport);
        }
        ConfigureServerClient obj=new ConfigureServerClient();
        obj.setBounds(170,50,600, 600);
        c.add(obj);
        this.addWindowListener(this);
        this.setTitle("emailPLUS");
        setVisible(true);
    }
    public MainFrame() {
        initComponents();
    }

    public void windowActivated(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public void windowClosed(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public void windowDeactivated(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public void windowDeiconified(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public void windowIconified(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public void windowOpened(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public void windowClosing(WindowEvent e) {
        
        DBOperations obj=new DBOperations();
        obj.addLogoutTime();
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuBar = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        miLogout = new javax.swing.JMenuItem();
        mnuProfile = new javax.swing.JMenu();
        miProfileAccountDetail = new javax.swing.JMenuItem();
        miProfilePersonalDetail = new javax.swing.JMenuItem();
        mnuUserMaintenance = new javax.swing.JMenu();
        miUserAccountDetail = new javax.swing.JMenuItem();
        miUserPersonalDetail = new javax.swing.JMenuItem();
        mnuEmailClient = new javax.swing.JMenu();
        miConfigureServerClient = new javax.swing.JMenuItem();
        mnuReport = new javax.swing.JMenu();
        miUserAccountReport = new javax.swing.JMenuItem();
        miUserPersonalReport = new javax.swing.JMenuItem();
        miUserActivityReport = new javax.swing.JMenuItem();
        miUserMailingReport = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuFile.setText("File");

        miLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        miLogout.setText("Logout");
        miLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLogoutActionPerformed(evt);
            }
        });
        mnuFile.add(miLogout);

        MenuBar.add(mnuFile);

        mnuProfile.setText("Profile");

        miProfileAccountDetail.setText("Profile Account Detail");
        miProfileAccountDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProfileAccountDetailActionPerformed(evt);
            }
        });
        mnuProfile.add(miProfileAccountDetail);

        miProfilePersonalDetail.setText("Profile Personal Detail");
        miProfilePersonalDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProfilePersonalDetailActionPerformed(evt);
            }
        });
        mnuProfile.add(miProfilePersonalDetail);

        MenuBar.add(mnuProfile);

        mnuUserMaintenance.setText("User Maintenance");

        miUserAccountDetail.setText("User Account Detail");
        miUserAccountDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUserAccountDetailActionPerformed(evt);
            }
        });
        mnuUserMaintenance.add(miUserAccountDetail);

        miUserPersonalDetail.setText("User Personal Detail");
        miUserPersonalDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUserPersonalDetailActionPerformed(evt);
            }
        });
        mnuUserMaintenance.add(miUserPersonalDetail);

        MenuBar.add(mnuUserMaintenance);

        mnuEmailClient.setText("Email Client");

        miConfigureServerClient.setText("Configure Server Client");
        miConfigureServerClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConfigureServerClientActionPerformed(evt);
            }
        });
        mnuEmailClient.add(miConfigureServerClient);

        MenuBar.add(mnuEmailClient);

        mnuReport.setText("Reports");

        miUserAccountReport.setText("User Account Report");
        miUserAccountReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUserAccountReportActionPerformed(evt);
            }
        });
        mnuReport.add(miUserAccountReport);

        miUserPersonalReport.setText("User Personal Report");
        miUserPersonalReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUserPersonalReportActionPerformed(evt);
            }
        });
        mnuReport.add(miUserPersonalReport);

        miUserActivityReport.setText("User Activity Report");
        miUserActivityReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUserActivityReportActionPerformed(evt);
            }
        });
        mnuReport.add(miUserActivityReport);

        miUserMailingReport.setText("User Mailing Report");
        miUserMailingReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUserMailingReportActionPerformed(evt);
            }
        });
        mnuReport.add(miUserMailingReport);

        MenuBar.add(mnuReport);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 213, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miUserAccountDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUserAccountDetailActionPerformed
        // TODO add your handling code here:
        c.removeAll();
        UserAcountDetail obj=new UserAcountDetail();
        obj.setBounds(170,50,600,600);
        c.add(obj);
        c.setVisible(false);
        c.setVisible(true);
}//GEN-LAST:event_miUserAccountDetailActionPerformed

    private void miUserAccountReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUserAccountReportActionPerformed
        // TODO add your handling code here:
        UserAccountReport obj2=new UserAccountReport();
        obj2.setVisible(true);
    }//GEN-LAST:event_miUserAccountReportActionPerformed

    private void miProfileAccountDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProfileAccountDetailActionPerformed
        // TODO add your handling code here:
        c.removeAll();
        ProfileAccountDetail obj=new ProfileAccountDetail();
        obj.setBounds(170,50,600, 600);
        c.add(obj);
        c.setVisible(false);
        c.setVisible(true);
    }//GEN-LAST:event_miProfileAccountDetailActionPerformed

    private void miProfilePersonalDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProfilePersonalDetailActionPerformed
        // TODO add your handling code here:
        c.removeAll();
        ProfilePersonalDetail obj=new ProfilePersonalDetail();
        obj.setBounds(170,50,600, 600);
        c.add(obj);
        c.setVisible(false);
        c.setVisible(true);
    }//GEN-LAST:event_miProfilePersonalDetailActionPerformed

    private void miUserPersonalDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUserPersonalDetailActionPerformed
        // TODO add your handling code here:
        c.removeAll();
        UserPersonalDetail obj=new UserPersonalDetail();
        obj.setBounds(170,50,600, 600);
        c.add(obj);
        c.setVisible(false);
        c.setVisible(true);
    }//GEN-LAST:event_miUserPersonalDetailActionPerformed

    private void miConfigureServerClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConfigureServerClientActionPerformed
        // TODO add your handling code here:
        c.removeAll();
        ConfigureServerClient obj=new ConfigureServerClient();
        obj.setBounds(170,50,600, 600);
        c.add(obj);
        c.setVisible(false);
        c.setVisible(true);
    }//GEN-LAST:event_miConfigureServerClientActionPerformed

    private void miUserPersonalReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUserPersonalReportActionPerformed
        // TODO add your handling code here:
        UserPersonalReport obj2=new UserPersonalReport();
        obj2.setVisible(true);
    }//GEN-LAST:event_miUserPersonalReportActionPerformed

    private void miUserActivityReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUserActivityReportActionPerformed
        // TODO add your handling code here:
        UserActivityReport obj2=new UserActivityReport();
        obj2.setVisible(true);
    }//GEN-LAST:event_miUserActivityReportActionPerformed

    private void miUserMailingReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUserMailingReportActionPerformed
        // TODO add your handling code here:
        UserMailingReport obj2=new UserMailingReport();
        obj2.setVisible(true);
    }//GEN-LAST:event_miUserMailingReportActionPerformed

    private void miLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLogoutActionPerformed
        // TODO add your handling code here:
        DBOperations obj=new DBOperations();
        obj.addLogoutTime();
        System.exit(0);
    }//GEN-LAST:event_miLogoutActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem miConfigureServerClient;
    private javax.swing.JMenuItem miLogout;
    private javax.swing.JMenuItem miProfileAccountDetail;
    private javax.swing.JMenuItem miProfilePersonalDetail;
    private javax.swing.JMenuItem miUserAccountDetail;
    private javax.swing.JMenuItem miUserAccountReport;
    private javax.swing.JMenuItem miUserActivityReport;
    private javax.swing.JMenuItem miUserMailingReport;
    private javax.swing.JMenuItem miUserPersonalDetail;
    private javax.swing.JMenuItem miUserPersonalReport;
    private javax.swing.JMenu mnuEmailClient;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuProfile;
    private javax.swing.JMenu mnuReport;
    private javax.swing.JMenu mnuUserMaintenance;
    // End of variables declaration//GEN-END:variables

}
