/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SentMailsPanel.java
 *
 * Created on 6 Jul, 2011, 3:49:33 PM
 */

package emailplus;

import emailplus.operations.DBOperations;
import java.util.ArrayList;
import javax.swing.JTable;
import emailplus.operations.UserMailBean;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;


/**
 *
 * @author Vishal
 */
public class SentMailsPanel extends javax.swing.JPanel implements ListSelectionListener{

    /** Creates new form SentMailsPanel */
    DBOperations obj=null;
    ArrayList al=null;
    int configId;
    String from;
    public SentMailsPanel() {
       initComponents();
        txtContent.setEditable(false);
        //configId=MaintainMailsFrame.configId;
        configId=MailAccountManager.configid;
       // configId=2;
                
        from=MailAccountManager.objBean.getUsername();
        obj=new DBOperations();
        al=obj.getSentMailsDetail(configId);
        //al=null;
        
        if(al.isEmpty())
        {
            lblMessage.setText("There are no items to show in this folders");
            SentMailTable.setEnabled(false);
            //JOptionPane.showMessageDialog(this, "no record", "Message", 1);
        }
        else
        {
            showSentMails();
            SentMailTable.getSelectionModel().addListSelectionListener(this);
        }
    }
    public void showSentMails()
    {
        String header[]={"From","Subject","Sent Date"};
        Object data[][]=new Object[al.size()][3];
        for(int i=0;i<al.size();i++)
        {
            UserMailBean objBean=(UserMailBean)al.get(i);
            data[i][0]=from;
            data[i][1]=objBean.getSubject();
            data[i][2]=objBean.getDate();
        }
        SentMailTable=new JTable(new DefaultTableStructure(data,header));
        jScrollPane.setViewportView(SentMailTable);
        p.setVisible(false);
        p.setVisible(true);

    }

    public void valueChanged(ListSelectionEvent e) {
        int i=SentMailTable.getSelectedRow();
        UserMailBean objBean=(UserMailBean)al.get(i);
        txtContent.setText(objBean.getContent());
        lblFrom.setText("From:   "+from);
        lblTo.setText("To:   "+objBean.getTo());
        lblSubject.setText("Subject:   "+objBean.getSubject());
        //System.out.println(i);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMessage = new javax.swing.JLabel();
        p = new javax.swing.JPanel();
        lblFrom = new javax.swing.JLabel();
        lblTo = new javax.swing.JLabel();
        lblSubject = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtContent = new javax.swing.JTextArea();
        jScrollPane = new javax.swing.JScrollPane();
        SentMailTable = new javax.swing.JTable();

        lblFrom.setText("From:");

        lblTo.setText("To:");

        lblSubject.setText("Subject:");

        txtContent.setColumns(20);
        txtContent.setRows(5);
        jScrollPane2.setViewportView(txtContent);

        SentMailTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "From", "To", "Sent Date"
            }
        ));
        jScrollPane.setViewportView(SentMailTable);

        javax.swing.GroupLayout pLayout = new javax.swing.GroupLayout(p);
        p.setLayout(pLayout);
        pLayout.setHorizontalGroup(
            pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSubject, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                    .addComponent(lblFrom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addComponent(lblTo, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(252, 252, 252))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE)
            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE)
        );
        pLayout.setVerticalGroup(
            pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLayout.createSequentialGroup()
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(p, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable SentMailTable;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblSubject;
    private javax.swing.JLabel lblTo;
    private javax.swing.JPanel p;
    private javax.swing.JTextArea txtContent;
    // End of variables declaration//GEN-END:variables

}
