/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UserAcountDetail.java
 *
 * Created on 7 Jul, 2011, 11:29:40 AM
 */


package emailplus;

/**
 *
 * @author Vishal
 */
import emailplus.operations.DBOperations;
import emailplus.operations.UsermasterBean;
import java.util.*;
import javax.swing.JOptionPane;
public class UserAcountDetail extends javax.swing.JPanel {

    /** Creates new form UserAcountDetail */
    String addupdateflag="";
    ArrayList al=null;
    DBOperations obj=null;
    int count=0;
    public UserAcountDetail() {
        initComponents();
        txtUserID.setEditable(false);
        disable(false);
        btnSave.setEnabled(false);
        obj=new DBOperations();
        al=obj.getAllUserAccountDetail();
        if(al.size()>0)
        {
            UsermasterBean objBean=(UsermasterBean)al.get(count);
            showRecords(objBean);
        }
    }
    public UserAcountDetail(int count) {
        initComponents();
        txtUserID.setEditable(false);
        disable(false);
        btnSave.setEnabled(false);
        this.count=count;
        obj=new DBOperations();
        al=obj.getAllUserAccountDetail();
        if(al.size()>0)
        {
            UsermasterBean objBean=(UsermasterBean)al.get(count);
            showRecords(objBean);
        }
    }
    public void showRecords(UsermasterBean objBean)
    {
        txtUserID.setText(String.valueOf(objBean.getUserId()));
        txtUsername.setText(objBean.getUsername());
        txtPassword.setText(objBean.getPassword());
        txtSecurityAnswer.setText(objBean.getSecurityAnswer());
        ddlUserType.setSelectedItem(objBean.getUserType());
        ddlUserStatus.setSelectedItem(objBean.getUserStatus());
        ddlSecurityQuestion.setSelectedItem(objBean.getSecurityQuestion());
    }
    public void disable(boolean vol)
    {
        txtUsername.setEditable(vol);
        txtPassword.setEditable(vol);
        txtSecurityAnswer.setEditable(vol);
        ddlUserType.setEnabled(vol);
        ddlUserStatus.setEnabled(vol);
        ddlSecurityQuestion.setEnabled(vol);
    }
    void clear()
    {
        txtUsername.setText("");
        txtPassword.setText("");
        txtSecurityAnswer.setText("");
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUserID = new javax.swing.JTextField();
        btnPersonalDetail = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        ddlUserType = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        ddlUserStatus = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        ddlSecurityQuestion = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        txtSecurityAnswer = new javax.swing.JTextField();
        btnFirst = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20));
        jLabel1.setText("User Account Detail");

        jLabel2.setText("User ID");

        btnPersonalDetail.setText("Personal Detail");
        btnPersonalDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonalDetailActionPerformed(evt);
            }
        });

        jLabel3.setText("Username");

        jLabel4.setText("Password");

        jLabel5.setText("User Type");

        ddlUserType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrator", "Employee" }));

        jLabel6.setText("User Status");

        ddlUserStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Active", "InActive" }));

        jLabel7.setText("Security Question");

        ddlSecurityQuestion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "What is your first school name?", "your favourite color?", "What is your hobby?" }));

        jLabel8.setText("Security Answer");

        btnFirst.setText("First");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnLast.setText("Last");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(211, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(188, 188, 188))
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFirst, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPrevious, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNext, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLast, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPersonalDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ddlUserStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ddlUserType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ddlSecurityQuestion, javax.swing.GroupLayout.Alignment.LEADING, 0, 189, Short.MAX_VALUE)
                                .addComponent(txtSecurityAnswer, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPersonalDetail))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ddlUserType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ddlUserStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ddlSecurityQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSecurityAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFirst)
                    .addComponent(btnPrevious)
                    .addComponent(btnNext)
                    .addComponent(btnLast))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addContainerGap(63, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
        if(al.size()>0)
        {
            count=0;
            UsermasterBean objBean=(UsermasterBean)al.get(count);
            showRecords(objBean);
        }
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
        if(count>0)
        {
            count--;
            UsermasterBean objBean=(UsermasterBean)al.get(count);
            showRecords(objBean);
        }
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        if(count<al.size()-1)
        {
            count++;
            UsermasterBean objBean=(UsermasterBean)al.get(count);
            showRecords(objBean);
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        if(al.size()>0)
        {
            count=al.size()-1;
            UsermasterBean objBean=(UsermasterBean)al.get(count);
            showRecords(objBean);
        }
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        disable(true);
        clear();
        int maxid=obj.getMaxId();
        txtUserID.setText(String.valueOf(maxid+1));
        btnSave.setEnabled(true);
        btnFirst.setEnabled(false);
        btnPrevious.setEnabled(false);
        btnNext.setEnabled(false);
        btnLast.setEnabled(false);
        btnUpdate.setEnabled(false);
        addupdateflag="add";
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        disable(true);
        btnSave.setEnabled(true);
        btnFirst.setEnabled(false);
        btnPrevious.setEnabled(false);
        btnNext.setEnabled(false);
        btnLast.setEnabled(false);
        btnAdd.setEnabled(false);
        addupdateflag="update";
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String result="";
        int flag=0;
        if(txtUsername.getText().equals("")||txtPassword.getPassword().toString().equals("")||txtSecurityAnswer.getText().equals(""))
        {
             JOptionPane.showMessageDialog(this,"No field should be empty","Error",2);
             return;
        }
        UsermasterBean objBean=new UsermasterBean();
        objBean.setUserId(Integer.parseInt(txtUserID.getText()));
        int i=txtUsername.getText().codePointAt(0);
        if(!((i>=65 & i<=90)||(i>=97 & i<=122)))
        {
            JOptionPane.showMessageDialog(this,"First character of username should be alphabet","Error",2);
            return;
        }
        objBean.setUsername(txtUsername.getText());
        if(txtPassword.getPassword().length<8)
        {
            JOptionPane.showMessageDialog(this,"password must be of 8 characters","Error",2);
             return;
        }
        objBean.setPassword(new String(txtPassword.getPassword()));
        objBean.setSecurityAnswer(txtSecurityAnswer.getText());
        objBean.setUserType(ddlUserType.getSelectedItem().toString());
        objBean.setSecurityQuestion(ddlSecurityQuestion.getSelectedItem().toString());
        objBean.setUserStatus(ddlUserStatus.getSelectedItem().toString());
        if (addupdateflag.equals("add"))
        {
            result=obj.addRecord(objBean);
            if(result.equals("failed"))
            {
                JOptionPane.showMessageDialog(this,"Record not added","Error",2);
            }
            else if(result.equals("exits"))
            {
                JOptionPane.showMessageDialog(this,"Username already exits","Error",2);
            }
            else if(result.equals("added"))
            {
                JOptionPane.showMessageDialog(this,"Record added","Message",1);
                flag=1;
                al=obj.getAllUserAccountDetail();
                count=al.size()-1;
                UsermasterBean objbean=(UsermasterBean)al.get(count);
                showRecords(objbean);
            }
        }
        else if(addupdateflag.equals("update"))
        {
            result=obj.updateRecord(objBean);
            if(result.equals("failed"))
            {
                JOptionPane.showMessageDialog(this,"Record not updated","Error",2);
            }
            else if(result.equals("exits"))
            {
                JOptionPane.showMessageDialog(this,"Username already exits","Error",2);
            }
            else if(result.equals("updated"))
            {
                JOptionPane.showMessageDialog(this,"Record updated","Message",1);
                flag=1;
                al=obj.getAllUserAccountDetail();
                UsermasterBean objbean=(UsermasterBean)al.get(count);
                showRecords(objbean);
            }
        }
        if(flag==1)
        {

            disable(false);
            btnFirst.setEnabled(true);
            btnLast.setEnabled(true);
            btnPrevious.setEnabled(true);
            btnAdd.setEnabled(true);
            btnNext.setEnabled(true);
            btnUpdate.setEnabled(true);
            btnSave.setEnabled(false);

        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        MainFrame.c.removeAll();
        MainFrame.c.setVisible(false);
        MainFrame.c.setVisible(true);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnPersonalDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonalDetailActionPerformed
        // TODO add your handling code here:
        MainFrame.c.removeAll();
        UserPersonalDetail up=new UserPersonalDetail(count);
        up.setBounds(170,50,600, 600);
        MainFrame.c.add(up);
        MainFrame.c.setVisible(false);
        MainFrame.c.setVisible(true);
    }//GEN-LAST:event_btnPersonalDetailActionPerformed
    public void addAction()
    {
        disable(true);
        clear();
        int maxid=obj.getMaxId();
        txtUserID.setText(String.valueOf(maxid+1));
        btnSave.setEnabled(true);
        btnFirst.setEnabled(false);
        btnPrevious.setEnabled(false);
        btnNext.setEnabled(false);
        btnLast.setEnabled(false);
        btnUpdate.setEnabled(false);
        addupdateflag="add";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPersonalDetail;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox ddlSecurityQuestion;
    private javax.swing.JComboBox ddlUserStatus;
    private javax.swing.JComboBox ddlUserType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtSecurityAnswer;
    private javax.swing.JTextField txtUserID;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}
